#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

LC_ALL=C

local_branch="$(git rev-parse --abbrev-ref HEAD)"

valid_branch_regex="^(feat\/[a-z0-9._-]+|fix\/[a-z0-9._-]+|dev|stage|main)$"

message="[ERROR] Current branch name doesn't comply with project's naming policy. Your commit will be rejected. Rename your branch to a valid name (feat/*|fix/*), or use one of the main branches (develop|stage|main), then try again."

if [[ ! $local_branch =~ $valid_branch_regex ]]
then
    echo "$message"
    exit 1
fi

exit 0